# Generated by Django 3.1.7 on 2021-03-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedometer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Pedometer',
        ),
    ]
