# Generated by Django 3.1.7 on 2021-03-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedometer', '0004_auto_20210320_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedometer',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
