# Generated by Django 3.1.7 on 2021-03-20 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pedometer', '0006_auto_20210320_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedometer',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 14, 54, 28, 232671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedometer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
