# Generated by Django 3.1.7 on 2021-03-20 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pedometer', '0007_auto_20210320_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedometer',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 15, 0, 8, 322008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedometer',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
