# Generated by Django 3.1.7 on 2021-03-20 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pedometer', '0010_auto_20210320_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedometer',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 16, 44, 42, 688343, tzinfo=utc)),
        ),
    ]
