# Generated by Django 3.1.7 on 2021-03-20 19:16

from django.db import migrations, models
import pedometer.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedometer', '0012_auto_20210320_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedometer',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='pedometer',
            name='steps',
            field=pedometer.models.IntegerRangeField(),
        ),
    ]
